Story
mikeycodingstuff/mikeycodingstuff.github.io pull request #5
Opened 2022-07-13 14:02 UTC by mikeycodingstuff

2022-07-13 14:46 UTC, ashleycoles requested changes
Really good stuff Mikey, a fair few comments here, but they are all really minor things. Really like your approach and general structure.

2022-07-13 14:46 UTC, ashleycoles commented on index.html
> +						<a href="#">>Live</a>
I would suggest adding a `target="_blank"` attribute to any external links on the portfolio.

This means that the link will be opened in a new tab, so they can see the github or live link, but without actually leaving your site

2022-07-13 14:46 UTC, ashleycoles commented on styles.css
> +	white-space: nowrap;
Seems like this rule isn't having any effect

2022-07-13 14:46 UTC, ashleycoles commented on styles.css
> +	margin-right: 20%;
Believe it should be safe to remove this margin-right. Because the h1 is aligning from the left (as per normal document flow) the left margin should be all thats needed

2022-07-13 14:46 UTC, ashleycoles commented on styles.css
> +span:hover {
I'd say that the selector here is a bit too general - it will apply to any span, while that may be fine for now, you might end up adding other spans elsewhere that need different styling.

Suggest making the selector more specific, something like `.header-text span` so the rules only apply to this one span.

2022-07-13 14:46 UTC, ashleycoles commented on styles.css
> +	justify-content: center;
Doesn't seem like this justify-content is doing anything

2022-07-13 14:46 UTC, ashleycoles commented on styles.css
> +}
It should already be left aligned

2022-07-13 14:46 UTC, ashleycoles commented on styles.css
> +.contact-container {
Suggest moving this down to the other contact styling, just to keep the CSS ordered in logical groups. 

Makes it a bit easier to find the CSS you're after

2022-07-13 14:46 UTC, ashleycoles commented on styles.css
> +p {
Selector is too generic, for example in the contact section you're having to overirde the background color. Instead you should make the selector specific to the section this `p` is in. 

You can still have a p selector in your css but it should only contain things that truly apply to all p tags

2022-07-13 14:46 UTC, ashleycoles commented on index.html
> +	<div>
I could be wrong (haven't tried it), but I don't think this div is needed

2022-07-13 14:46 UTC, ashleycoles commented on styles.css
> +	width: 100%;
You should be able to remove this width.

Flex acts like block, meaning it will automatically take up all available width

2022-07-13 14:46 UTC, ashleycoles commented on styles.css
> +.contact-container {
In fact it looks like contact-container no longer exists in your HTML - should delete this whole bit

2022-07-13 14:46 UTC, ashleycoles commented on index.html
> +			</p>
Check indents here.

2022-07-14 09:15 UTC, charliecog reviewed
Looks great, really solid build, almost there

General comments:
- about me image is displaying higher than the about me text - if its a design decision then thats ok, if you want it to be level then will need addressing

2022-07-14 09:15 UTC, charliecog commented on index.html
> +  <link rel="stylesheet" href="styles.css">
need to move your styles.css link to below the google font link to be the last one referenced

2022-07-14 09:15 UTC, charliecog commented on index.html
> +				<br />
use css instead of br tags - margin and padding. Pls remove all br tags in your html (do a cmd + f to find them all)

2022-07-14 09:15 UTC, charliecog commented on styles.css
> +p {
+1 as it looks like this hasnt been actioned yet

2022-07-14 12:45 UTC, merged